### ISSUE TITLE
BOM mismatch between Value and Device - IC2 3.3V regulator - line 31

### ISSUE THREAD

**Issue by bitbangr** [jcchurch13/Mechaduino-Hardware#6]
BOM Line 31 shows 3.3V regulator AP2112K-3.3 as the value however the specified device is AP2202-ADJ.  

The AP2202-ADJ needs additional circuitry on pin 4 to set the correct output voltage. 

Perhaps update the BOM to reflect the correct device?

1   AP2112K-3.3               AP2202-ADJ                             SOT23-5@1                     IC2

**Comment by jcchurch13** [comment]
Fixed, thank you!
-Joe
