### ISSUE TITLE
R6, should this be a 10k?

### ISSUE THREAD

**Issue by thantik** [jcchurch13/Mechaduino-Hardware#7]
There are multiple places that I'm seeing a 10k pullup on the RESET line:

https://cdn.sparkfun.com/datasheets/Dev/Arduino/Boards/sparkfun-samd21-mini-breakout-v10.pdf

http://www.atmel.com/Images/Atmel-42181-SAM-D21_Datasheet.pdf -- Page 1022 under 39.4. External Reset Circuit

But on the schematic and board, R6 is listed as a 330ohm.  This is a pretty strong pullup, is there a reason for the deviation?

**Comment by jcchurch13** [comment]
Hi!  R6 is used as a current limiting resistor here (similar to the second resistor in the 39.4 example above).  R1 acts as the pullup (100k).
