### ISSUE TITLE
Opensource.com article

### ISSUE THREAD

**Issue by spotrh** [jcchurch13/Mechaduino-Hardware#9]
Joe,

Apologies for opening a github issue, but I couldn't find an email address for you. I'm writing an article for opensource.com on some of the best open source hardware innovations in 3d printing in 2016, and I want to feature the Mechaduino. Would you be able to point me to a picture of the Mechaduino (maybe the "banana" picture from the kickstarter page) that I could use under a Creative Commons license (CC-BY-SA would be ideal)?

Thanks in advance,

Tom Callaway tcallawa@redhat.com

**Comment by jcchurch13** [comment]
Feel free to use any of the photos on our hackaday.io page:

https://hackaday.io/project/11224-mechaduino

All Mechaduino related materials are released under the Creative Commons Attribution Share-Alike 4.0 License!
